@baseUrl = http://localhost:3000
@userId = 6a4e22134f37f16f5b57d44c
### TEST API
GET {{baseUrl}}

###CREATE USER

POST {{baseUrl}}/users
Content-Type: application/json

{
    
    "email": "adi112@gmail.com",
    "password": "12345678"
}

### Get all users
GET {{baseUrl}}/users

### Get users by id
GET {{baseUrl}}/users/{{userId}}

### update user by id
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
    "email": "adi111@gmail.com"
}

### delete user by Id

DELETE {{baseUrl}}/users/{{userId}}
