@baseUrl = http://localhost:3000
@userId = 6a48f11fd32aa6bff78ed1f8
### TEST API
GET {{baseUrl}}

###CREATE USER

POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "aditya",
    "email": "adi12@gmail.com",
    "password": "12345678"
}

### Get all users
GET {{baseUrl}}/users

### Get users by id
GET {{baseUrl}}/users/{{userId}}

### update user by id
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
    "name": "aditya singh pqr"
}

### delete user by Id

DELETE {{baseUrl}}/users/{{userId}}
